#undef SCENE_TEXTURES_DISABLED
#define SCENE_TEXTURES_DISABLED 1

#include "/Engine/Private/Common.ush"
#include "/Engine/Generated/Material.ush"
#include "/Engine/Generated/VertexFactory.ush"

struct FFoliageBakerDepthCorrectVSToPS
{
	FVertexFactoryInterpolantsVSToPS FactoryInterpolants;
	float4 PixelPosition : TEXCOORD6;
#if USE_WORLD_POSITION_EXCLUDING_SHADER_OFFSETS
	float3 PixelPositionExcludingWPO : TEXCOORD7;
#endif
	FStereoVSOutput StereoOutput;
	INVARIANT_OUTPUT float4 Position : SV_POSITION;
};

void MainVS(
	FVertexFactoryInput Input,
	out FFoliageBakerDepthCorrectVSToPS Output)
{
	StereoSetupVF(Input, Output.StereoOutput);
	FVertexFactoryIntermediates VFIntermediates = GetVertexFactoryIntermediates(Input);
	float4 WorldPosition = VertexFactoryGetWorldPosition(Input, VFIntermediates);
	float4 WorldPositionExcludingWPO = WorldPosition;
	half3x3 TangentToLocal = VertexFactoryGetTangentToLocal(Input, VFIntermediates);
	FMaterialVertexParameters VertexParameters = GetMaterialVertexParameters(
		Input,
		VFIntermediates,
		WorldPosition.xyz,
		TangentToLocal);
	WorldPosition.xyz += GetMaterialWorldPositionOffset(VertexParameters);
	float4 RasterizedWorldPosition = VertexFactoryGetRasterizedWorldPosition(
		Input,
		VFIntermediates,
		WorldPosition);
	Output.Position = INVARIANT(mul(RasterizedWorldPosition, ResolvedView.TranslatedWorldToClip));
	Output.FactoryInterpolants = VertexFactoryGetInterpolantsVSToPS(
		Input,
		VFIntermediates,
		VertexParameters);
	Output.PixelPosition = WorldPosition;
#if USE_WORLD_POSITION_EXCLUDING_SHADER_OFFSETS
	Output.PixelPositionExcludingWPO = WorldPositionExcludingWPO.xyz;
#endif
}

void MainPS(
	FVertexFactoryInterpolantsVSToPS Interpolants,
	float4 PixelPosition : TEXCOORD6,
#if USE_WORLD_POSITION_EXCLUDING_SHADER_OFFSETS
	float3 PixelPositionExcludingWPO : TEXCOORD7,
#endif
	in FStereoPSInput StereoInput,
	in INPUT_POSITION_QUALIFIERS float4 SvPosition : SV_Position
	OPTIONAL_IsFrontFace
	OPTIONAL_OutDepthConservative
	,out float4 OutColor : SV_Target0)
{
	StereoSetupPS(StereoInput);
	FMaterialPixelParameters MaterialParameters = GetMaterialPixelParameters(Interpolants, SvPosition);
	FPixelMaterialInputs PixelMaterialInputs;
#if USE_WORLD_POSITION_EXCLUDING_SHADER_OFFSETS
	float4 ScreenPosition = SvPositionToResolvedScreenPosition(SvPosition);
	float3 TranslatedWorldPosition = SvPositionToResolvedTranslatedWorld(SvPosition);
	CalcMaterialParametersEx(
		MaterialParameters,
		PixelMaterialInputs,
		SvPosition,
		ScreenPosition,
		bIsFrontFace,
		TranslatedWorldPosition,
		PixelPositionExcludingWPO);
#else
	CalcMaterialParameters(MaterialParameters, PixelMaterialInputs, SvPosition, bIsFrontFace);
#endif
#if OUTPUT_PIXEL_DEPTH_OFFSET
	ApplyPixelDepthOffsetToMaterialParameters(MaterialParameters, PixelMaterialInputs, OutDepth);
#endif
	GetMaterialCoverageAndClipping(MaterialParameters, PixelMaterialInputs);
	OutColor = float4(GetMaterialEmissive(PixelMaterialInputs), saturate(SvPosition.z));
}
